### DISCUSSION TITLE
Nested objects in yaml become AnonymousSchema

### DISCUSSION THREAD

**Discussion by fr-th** [asyncapi/modelina#1953] [Q&A]
Greetings, 

I noticed when generating C# models based on a provided yaml contract that, if nested objects were present in the specifications this would result in AnonymousSchema being created. :

Contract : 
```
...
property1: 
  type: string
  nullable: true
nestedObjectName:
  type: object
  properties:
    objectProperty1:
      type: string
      nullable: true
    objectProperty2:
      type: string
      nullable: true
restOfProperties:
  type: string
  nullable: true
...
```

Results in : 
```
...
public string? Property1{ get; set; }
public AnonymousSchema_212? NestedObjectName{ get; set; }
public string? RestOfProperties { get; set; }
...
```

And the object : 
```
public partial class AnonymousSchema_212
{
  public string? ObjectProperty1{ get; set; }
  public string? ObjectProperty2{ get; set; }
}
```

This is not great for code readability afterwards.
I wanted to know if there was a way around that or a solution to improve that ? I did not find any in the documentation so far.

Could it be possible to generate the class using the name of the property, maybe with a prefix/suffix to avoid issue ? 

Thanks in advance
