### ISSUE TITLE
Uppercase enum/union member names handled as reserved keywords [RustGenerator]

### ISSUE THREAD

**Issue by leigh-johnson** [asyncapi/modelina#1030]
#### Describe the bug

Two issues with the following schema:

1. The following schema generates an enum with a `ReservedStatic` member, since `static` is a reserved keyword in Rust. However, `Static` is perfectly valid as an enum member name after an uppercase transformation is performed. 

I'm guessing this bug applies to other keywords used as Enum/Union member names.

2. `EnabledMinusRuntime` and `LinkedMinusRuntime` should just be `EnabledRuntime` `LinkedRuntime`

```
    SystemdUnitFileState:
      type: string
      additionalProperties: false
      enum:
        - "enabled"
        - "enabled-runtime"
        - "linked"
        - "linked-runtime"
        - "masked"
        - "masked-runtime"
        - "static"
        - "disabled"
        - "invalid"
```

```rust
// SystemdUnitFileState represents a SystemdUnitFileState model.
#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
pub enum SystemdUnitFileState {
    #[serde(rename="enabled")]
    Enabled,
    #[serde(rename="enabled-runtime")]
    EnabledMinusRuntime,
    #[serde(rename="linked")]
    Linked,
    #[serde(rename="linked-runtime")]
    LinkedMinusRuntime,
    #[serde(rename="masked")]
    Masked,
    #[serde(rename="masked-runtime")]
    MaskedMinusRuntime,
    #[serde(rename="static")]
    ReservedStatic,
    #[serde(rename="disabled")]
    Disabled,
    #[serde(rename="invalid")]
    Invalid,
}
impl Default for SystemdUnitFileState {
    fn default() -> SystemdUnitFileState {
        SystemdUnitFileState::Enabled
    }
}
```

#### Expected behavior

The following code should be generated:
```rust
// SystemdUnitFileState represents a SystemdUnitFileState model.
#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
pub enum SystemdUnitFileState {
    #[serde(rename="enabled")]
    Enabled,
    #[serde(rename="enabled-runtime")]
    EnabledRuntime,
    #[serde(rename="linked")]
    Linked,
    #[serde(rename="linked-runtime")]
    LinkedRuntime,
    #[serde(rename="masked")]
    Masked,
    #[serde(rename="masked-runtime")]
    MaskedRuntime,
    #[serde(rename="static")]
    Static,
    #[serde(rename="disabled")]
    Disabled,
    #[serde(rename="invalid")]
    Invalid,
}
impl Default for SystemdUnitFileState {
    fn default() -> SystemdUnitFileState {
        SystemdUnitFileState::Enabled
    }
}
```
