### ISSUE TITLE
"name" property is a reserved keyword in Typescript generator

### ISSUE THREAD

**Issue by leigh-johnson** [asyncapi/modelina#1053]
#### Describe the bug
I noticed one of my Typescript models is being generated with a `reserved_name` property instead of just `name` - even though `name` isn't a reserved keyword in Typescript.

#### How to Reproduce

version: `1.0.0-next.36`

1. Given the following schema:

```
  schemas:
    Camera:
      name: Camera
      type: object
      additionalProperties: false
      properties:
        index:
          type: integer
        name:
          type: string
        label:
          type: string
      required:
        - index
        - name
        - label
```

2. Generate a Typescript model. Notice: `reserved_name` is rendered as the property name.

```typescript
export interface Camera {
    index: number;
    reserved_name: string;
    label: string;
}
```

Here's my generator config, just in case that's relevant:
```typescript
const generator = new TypeScriptFileGenerator({
  renderTypes: true,
  modelType: "interface",
  constraints: {
    propertyKey: typeScriptDefaultPropertyKeyConstraints({
      NAMING_FORMATTER: (name) => {
        return name;
      }
    })
  }
});
```

3. Serializing Typescript model as JSON -> deserializing in Rust fails, since the Rust model expects this field to be called `name`

```rust
// Camera represents a Camera model.
#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
pub struct Camera {
    #[serde(rename="index")]
    pub index: i32,
    #[serde(rename="name")]
    pub name: String,
    #[serde(rename="label")]
    pub label: String,
}

impl Camera {
    pub fn new(index: i32, name: String, label: String) -> Camera {
        Camera {
            index,
            name,
            label,
        }
    }
}
```

#### Expected behavior

The following Typescript interface should be generated, given the schema above:

```
export interface Camera {
    index: number;
    name: string;
    label: string;
}
```
