### ISSUE TITLE
JSON Schema enum pattern to define enum key and value with oneOf

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#1121]
#### Reason/Context
A new pattern emerged for JSON Schema that enable you to define enums with key and value.

```
Severity:
  type: integer
  oneOf:
    - title: HIGH
      const: 2
      description: An urgent problem
    - title: MEDIUM
      const: 1
    - title: LOW
      const: 0
      description: Can wait forever
```

Which expect to be rendered as the following:

```
public enum Source {
  HIGH(2), MEDIUM(1), LOW(0);
}
```

But currently is split out into 3 enums:
```
public enum Low {
  NUMBER_0((int)0);

  private int value;

  Low(int value) {
    this.value = value;
  }
  ...
}
```

To solve this I expect the following change is needed:
1. We need to adapt the CommonModel to allow enums to be defined with key and value instead of just value.
2. We need to adapt the CommonModel to MetaModel conversion to respect the new key and value
3. We need to adapt the interpreter to look for this pattern in oneOf and anyOf, maybe a post process of the keyword interpretation we can merge all enums together.
