### ISSUE TITLE
TypeScript generator produce enum/union for constant

### ISSUE THREAD

**Issue by Fyzu** [asyncapi/modelina#1447]
#### Describe the bug
For`const` property, an enum or union is always created.
It would be more convenient if such types were inlined as TypeScript does when using `as const`.

```ts
interface KeepaliveMessage {
  type: AnonymousSchema_1;
  channel: AnonymousSchema_2;
}
export { KeepaliveMessage };
```

For example, `openapi-typescript` generator generates:
```ts
{
    KeepaliveMessage: {
      /** @constant */
      type: "KEEPALIVE";
    };
}
```

#### How to Reproduce

Async API schema: 
```yml
messages:
  KeepaliveMessage:
    payload:
      $id: KeepaliveMessage
      type: object
      required: [type, channel]
      properties:
          type:
            const: KEEPALIVE
          channel:
            type: number
            const: 0
```

#### Expected behavior
I expect there to be an inline type:
```ts
interface KeepaliveMessage {
  type: "KEEPALIVE";
  channel: 0;
}
export { KeepaliveMessage };
```
