### ISSUE TITLE
asyncapi CLI model generation fails if AnyModel is used

### ISSUE THREAD

**Issue by PeteAudinate** [asyncapi/modelina#1561]
#### Describe the bug
If a schema includes an "Any" type, the code in `CommonModelToMetaModel.js` logs an error then returns an AnyModel (https://github.com/asyncapi/modelina/blob/68e9a23f607ffd2028aafc84d9f9ab6239cee957/src/helpers/CommonModelToMetaModel.ts#L95). 

This error logging causes the `asyncapi generate model` command to abort and not generate any output.

#### How to Reproduce
With the following:
```yml
# minimal.yml
asyncapi: 2.6.0

info:
  title: test
  version: 1.0.0

channels:
  hello:
    publish:
      message:
        payload:
          type: object
          properties:
            test: {}
```

Running:
```sh
asyncapi generate models rust minimal.yml -o minimal
```

Produces:
```sh
Error: Failed to convert to MetaModel, defaulting to AnyModel
```

..and no generated files.

#### Expected behavior
The above should generate the rust model with a `serde_json::Value` type.
If I manually change the `Logger.error` to `Logger.warn` in `CommonModelToMetaModel.js`, it works as expected.
