### ISSUE TITLE
Incorrect C# code generated for Enum in System.Text.Json JsonConverter.

### ISSUE THREAD

**Issue by RowlandBanks** [asyncapi/modelina#1783]
#### Describe the bug
When generating `System.Text.Json` compatible models, the generated code does not compile.

#### How to Reproduce

```yml
asyncapi: 2.0.0
info:
  title: Person Service
  version: 1.0.0
channels:
  person:
    subscribe:
      message:
        payload:
          type: object
          $id: Person
          properties:
            Name:
              type: string
            FavoriteColor:
              type: string
              $id: Colors
              enum:
                - Red
                - Green
                - Blue
```

Run the following command to generate the models
```ps
docker run --rm -it --user=root `
   -v .:/app/input `
   -v c:\temp\modelina\bug1\models:/app/output  `
   asyncapi/cli:1.5.2 `
   generate models csharp `
   -o /app/output `
   /app/input/PersonService.yaml `
   --namespace=MyTest `
   --csharpSystemJson
```

#### Expected behavior
Compilable code that correctly serializes the `FavouriteColor` property should be generated.

#### Actual Behaviour

The generated code is incorrect - specifically in the following method:

```c#
public override void Write(Utf8JsonWriter writer, Person value, JsonSerializerOptions options)
{
  // snip
  var properties = value.GetType().GetProperties().Where(prop => prop.Name != "AdditionalProperties");

  writer.WriteStartObject();

  // snip
  if(value.FavoriteColor != null) {
    // write property name and let the serializer serialize the value itself
    writer.WritePropertyName("FavoriteColor");

    // ERROR: value.Colors does not exist. It should be value.FavoriteColor.
    JsonSerializer.Serialize(writer, value.Colors?.GetValue(), options);
  }
  // snip
}
```
