### ISSUE TITLE
[BUG] A field defined with type as `number`, format: int32 is generated as a Double field  by the Kotlin Generator.

### ISSUE THREAD

**Issue by gitankit7** [asyncapi/modelina#2110]
### Describe the bug.

```
        durationInMonths:
          type:
            - number
            - 'null'
          example: 36
          format: int32
          description: Duration of contract in months
 ```
When the Kotlin generator is run on this, the field generated is of type Double.

```
val durationInMonths: Double? = null,
```

### Expected behavior

The field should ideally be an Integer
```
val durationInMonths: Int? = null,
```

### Screenshots

<img width="576" alt="Screenshot 2024-10-23 at 11 22 42 AM" src="https://github.com/user-attachments/assets/3ade8e72-1370-40b6-99a7-0ba2537a4e14">
<img width="345" alt="Screenshot 2024-10-23 at 11 22 50 AM" src="https://github.com/user-attachments/assets/35f0c12b-7151-42a4-b1d0-52b47141f689">

### How to Reproduce

1. Have a yml file with type as number
2. Run the kotlin generator
3. you will get the type of field as Double

### 🥦 Browser

None

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None
