### ISSUE TITLE
[BUG] Nullable but required field in Go

### ISSUE THREAD

**Issue by condorcet** [asyncapi/modelina#2184]
### Describe the bug.

Previously nullable types were supported in scope of this issue https://github.com/asyncapi/modelina/issues/1418

But for now if field is required but nullable, it will not use the reference as expected.

For example if we have such schema

```
    schemaWithNullable:
      type: object
      required:
        - nullable_number
      properties:
        nullable_number:
          type:
            - number
            - "null"
``` 

The result will be this

```
type EventWithNullable struct {
  NullableNumber float64 `json:"nullable_number"` // should be *float64
}
```

Looks like in [this condition](https://github.com/asyncapi/modelina/blob/master/src/generators/go/GoConstrainer.ts#L87) must be used OR instead of AND (as the Java generator does)
```
  if (constrainedModel.options.isNullable || !required) {
    return typeWhenNullableOrOptional;
  }
```

### Expected behavior

For nullable but required field in schema, the result should be generated with reference type, instead of value.

### Screenshots

-

### How to Reproduce

1. Grab schema with nullable and required type above.
2. Generate Go code.
3. Check appropriate field in generated Go code.

### 🥦 Browser

None

### 👀 Have you checked for similar open issues?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [x] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None
