### ISSUE TITLE
Render Go enum values

### ISSUE THREAD

**Issue by felixjung** [asyncapi/modelina#647]
#### Reason/Context

Currently, Modeling seems to not render the values an enum type can take in Go.

For example

```yaml
properties:
  status:
    $id: Status
    type: string
    enum:
      - foo
      - bar
```

will only result in

```go
type Status string
```

While there are different approaches on how to deal with enums in Go, modelina could provide a simple standard approach, where the possible values are defined as constant strings. This would look as follows.

```go
type Status string

const (
  StatusFoo Status = "foo"
  StatusBar = "bar"
)
```

#### Description

- Update the Enum Renderer to render the values.
- This shouldn't be a breaking change as we are only generating additional code.
