### ISSUE TITLE
Type error when `type` is omitted in schemas in AsyncAPI spec

### ISSUE THREAD

**Issue by YushiOMOTE** [asyncapi/modelina#875]
#### Describe the bug

If one of the schemas in the AsyncAPI spec is missing `type`, type error happens as `schemaUid` is undefined.

For example, given this schema,

```yaml
asyncapi: 2.0.0
id: "https://github.com/yushiomote/hoge"
info:
  title: "Test"
  version: 2.0.0
defaultContentType: application/json
channels:
  hello:
    publish:
      message:
        name: hello
        payload:
          # type: object <- The issue happens if this is missing
          properties:
            data: { type: string }
```

this error happens:

```
/Users/yushi.omote/dev/model-play/modelina/src/processors/AsyncAPIInputProcessor.ts:66
    if (schemaUid.includes('<anonymous-schema')) {
                  ^
TypeError: Cannot read properties of undefined (reading 'includes')
```

This error doesn't happen on `master`. Omitting `type` isn't handled as an error in other tools like asyncapi studio.

![image](https://user-images.githubusercontent.com/3733915/189772741-1de9baea-4ff9-49fb-9b9a-4825ddf688f3.png)

#### How to Reproduce

See the description above.

#### Expected behavior

The spec should be processed without error as the type is `object`.
